//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismCMS.TranslateResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NoticeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoticeResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TourismCMS.TranslateResources.NoticeResource", typeof(NoticeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 可用的关键词! 的本地化字符串。
        /// </summary>
        public static string AVAILALE_KEYWORD {
            get {
                return ResourceManager.GetString("AVAILALE_KEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败! 的本地化字符串。
        /// </summary>
        public static string DONE_FAILURE {
            get {
                return ResourceManager.GetString("DONE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功! 的本地化字符串。
        /// </summary>
        public static string DONE_SUCCESS {
            get {
                return ResourceManager.GetString("DONE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件导出失败! 的本地化字符串。
        /// </summary>
        public static string EXPORT_FAILURE {
            get {
                return ResourceManager.GetString("EXPORT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件导出成功! 的本地化字符串。
        /// </summary>
        public static string EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failure 的本地化字符串。
        /// </summary>
        public static string FAILURE {
            get {
                return ResourceManager.GetString("FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在! 的本地化字符串。
        /// </summary>
        public static string HAS_EXISIT {
            get {
                return ResourceManager.GetString("HAS_EXISIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在相同关键词(同一景区不能添加相同关键词)！ 的本地化字符串。
        /// </summary>
        public static string HAS_EXIST_KEYWORD {
            get {
                return ResourceManager.GetString("HAS_EXIST_KEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆失败！ 的本地化字符串。
        /// </summary>
        public static string LOGIN_FAILURE {
            get {
                return ResourceManager.GetString("LOGIN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆成功! 的本地化字符串。
        /// </summary>
        public static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误! 的本地化字符串。
        /// </summary>
        public static string PWD_ERR {
            get {
                return ResourceManager.GetString("PWD_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有子节点,不能删除! 的本地化字符串。
        /// </summary>
        public static string REFERENCED_SON {
            get {
                return ResourceManager.GetString("REFERENCED_SON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败! 的本地化字符串。
        /// </summary>
        public static string REGIST_FAILURE {
            get {
                return ResourceManager.GetString("REGIST_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册成功! 的本地化字符串。
        /// </summary>
        public static string REGIST_SUCCESS {
            get {
                return ResourceManager.GetString("REGIST_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 success 的本地化字符串。
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入不一致! 的本地化字符串。
        /// </summary>
        public static string TWICE_DIFFERENT {
            get {
                return ResourceManager.GetString("TWICE_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未评审! 的本地化字符串。
        /// </summary>
        public static string UN_REVIEWED {
            get {
                return ResourceManager.GetString("UN_REVIEWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败! 的本地化字符串。
        /// </summary>
        public static string UPDATE_FAILURE {
            get {
                return ResourceManager.GetString("UPDATE_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功! 的本地化字符串。
        /// </summary>
        public static string UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新版本更新! 的本地化字符串。
        /// </summary>
        public static string UPDATE_VERSION {
            get {
                return ResourceManager.GetString("UPDATE_VERSION", resourceCulture);
            }
        }
    }
}
