//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismCMS.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteOrder
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public string GuestName { get; set; }
        public string GuestPhone { get; set; }
        public Nullable<int> AdultNum { get; set; }
        public Nullable<double> AdultOriginalPrice { get; set; }
        public Nullable<double> AdultSellPrice { get; set; }
        public Nullable<int> ChildNum { get; set; }
        public Nullable<double> ChildOriginalPrice { get; set; }
        public Nullable<double> ChildSellPrice { get; set; }
        public Nullable<System.DateTime> BookTime { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> ProxyIncome { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> BalanceDate { get; set; }
        public Nullable<int> CollectMoneyStatus { get; set; }
        public Nullable<System.DateTime> CollectMoneyDate { get; set; }
        public Nullable<int> ReviewStatus { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> HandlerId { get; set; }
        public Nullable<int> CheckerId { get; set; }
        public string BalanceRemark { get; set; }
        public string CollectMoneyRemark { get; set; }
        public Nullable<int> BalanceStatus { get; set; }
        public string Settlement { get; set; }
        public Nullable<double> ExtrasOriginPrice { get; set; }
        public Nullable<double> ExtrasSellPrice { get; set; }
        public Nullable<int> modifier { get; set; }
        public Nullable<int> ModifierId { get; set; }
    }
}
