//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回到登陆 的本地化字符串。
        /// </summary>
        internal static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        internal static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误! 的本地化字符串。
        /// </summary>
        internal static string CaptchaErrorMessage {
            get {
                return ResourceManager.GetString("CaptchaErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该邮箱已经重复注册! 的本地化字符串。
        /// </summary>
        internal static string DuplicateRegister {
            get {
                return ResourceManager.GetString("DuplicateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱地址 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        internal static string EmailOrPasswordErrorMessage {
            get {
                return ResourceManager.GetString("EmailOrPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入您要找回的账号（邮箱） 的本地化字符串。
        /// </summary>
        internal static string EnterYourAccountEmail {
            get {
                return ResourceManager.GetString("EnterYourAccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找回密码 的本地化字符串。
        /// </summary>
        internal static string FindPassword {
            get {
                return ResourceManager.GetString("FindPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忘记密码？ 的本地化字符串。
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我同意 的本地化字符串。
        /// </summary>
        internal static string Iagreen {
            get {
                return ResourceManager.GetString("Iagreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填入下列信息 的本地化字符串。
        /// </summary>
        internal static string InputInfos {
            get {
                return ResourceManager.GetString("InputInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 营业执照编号 的本地化字符串。
        /// </summary>
        internal static string LisenceNumber {
            get {
                return ResourceManager.GetString("LisenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息不能为空！ 的本地化字符串。
        /// </summary>
        internal static string LoginModelStateErrorMessage {
            get {
                return ResourceManager.GetString("LoginModelStateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主营业务 的本地化字符串。
        /// </summary>
        internal static string MainBusiness {
            get {
                return ResourceManager.GetString("MainBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商家注册 的本地化字符串。
        /// </summary>
        internal static string MerchantRegister {
            get {
                return ResourceManager.GetString("MerchantRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入密码不一致! 的本地化字符串。
        /// </summary>
        internal static string PasswordConflict {
            get {
                return ResourceManager.GetString("PasswordConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩趣商家用户协议 的本地化字符串。
        /// </summary>
        internal static string PlayFunMerchantUeragremment {
            get {
                return ResourceManager.GetString("PlayFunMerchantUeragremment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我想注册 的本地化字符串。
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败! 的本地化字符串。
        /// </summary>
        internal static string RegisterFailure {
            get {
                return ResourceManager.GetString("RegisterFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册成功! 的本地化字符串。
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我 的本地化字符串。
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再输一次密码 的本地化字符串。
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重填 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送给我 的本地化字符串。
        /// </summary>
        internal static string SendToMe {
            get {
                return ResourceManager.GetString("SendToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string TelePhone {
            get {
                return ResourceManager.GetString("TelePhone", resourceCulture);
            }
        }
    }
}
